/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PDFcipher;

import org.junit.Test;
import static org.junit.Assert.*;
import java.security.NoSuchAlgorithmException;
import javax.crypto.NoSuchPaddingException;
import javax.crypto.Cipher;

public class EncryptTest {
    @Test public void testEncrpytMethod() {
        EncryptKey classUnderTest = new EncryptKey();
        byte[] data = "test".getBytes();
        int blahb = 0;
        Cipher cipher = null;
        try{ cipher = Cipher.getInstance("RSA/ECB/PKCS1Padding"); }
        catch(NoSuchAlgorithmException | NoSuchPaddingException ex) {  System.out.println(ex.getMessage()); }
        //assertThat(cipher, classUnderTest.encryptMethod(data, blahb, cipher));
    }

}
